### ISSUE TITLE
sample.tex contains capitalised keywords

### ISSUE THREAD

**Issue by gittar** [JmlrOrg/jmlr-style-file#4]
The list of common formatting errors at https://www.jmlr.org/format/formatting-errors.html states:

> Keyword: Please add keywords to your article using \begin{keywords} ... \end{keywords} after your abstract. **They should not be capitalised**, ...

The file sample.tex contains this, however:
```
\begin{keywords}
  Bayesian Networks, Mixture Models, Chow-Liu Trees
\end{keywords}
```
According to the above guidelines the example should probably rather be as follows:
```
\begin{keywords}
  Bayesian networks, mixture models, Chow-Liu trees
\end{keywords}
```

**Comment by fabianp** [comment]
fixed, thanks!

**Comment by gittar** [comment]
Great, thank you.
